apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-default-dizu
  name: dizu
spec:
  replicas: 3
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-default-dizu
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-default-dizu
    spec:
      containers:
      - image: markusdhs/proddizu:1cfc4bf9f363b8544d61c6430385159ac225a2ca
        imagePullPolicy: Always
        name: container-0
        ports:
        - containerPort: 80
          name: test
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
